### ISSUE TITLE
Student Account

### ISSUE THREAD

**Issue by ellamaemontilla** [Moralde-Sama/DNES#13]
![image](https://user-images.githubusercontent.com/46624318/52910027-85bd3e80-32cc-11e9-9703-c9b3e7e534cb.png)

wala daw view grade ana ella

**Comment by Moralde-Sama** [comment]
ang view grade naa sa course taken. "My 2019 Schedule" = Nag klase pa

**Comment by astraea19** [comment]
I see thanks
